---
# ansible-vault    til opbevaring af private keys, passwords etc

# ansible-playbook -k -i hosts playbook_install_crontab.yml -v
# ansible all -i hosts -k -m ansible.builtin.setup -u pi

# --extra-vars "xxx=yyy"

- name: Configure WiFi
  hosts: QEQ-ERT-02-RPi3
  remote_user: pi
  become: true
  vars:
    enable_wifi: false
    finally_enable_ofs_bootro: false

  tasks:
    - name: Set overlayfs and bootro to disabled
      ansible.builtin.include_role:
        name: configure_overlayfs_and_bootro
      vars:
        enable_bootro: false
        enable_overlayfs: false
        allow_reboot: true

    # ==============================================================
    # Configure WiFi
    # ==============================================================
    - name: Configure WiFi
      ansible.builtin.include_role: 
        name: configure_wifi
      vars:
        allow_reboot: false

    - name: Set overlayfs and bootro to enabled
      ansible.builtin.include_role:
        name: configure_overlayfs_and_bootro
      vars:
        enable_bootro: "{{ finally_enable_ofs_bootro }}"
        enable_overlayfs: "{{ finally_enable_ofs_bootro }}"
        allow_reboot: true

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: 
        - "rpi_overlay_now: {{ rpi_overlay_now }}"
        - "rpi_overlay_conf: {{ rpi_overlay_conf }}"
        - "rpi_bootro_now: {{ rpi_overlay_now }}"
        - "rpi_bootro_conf: {{ rpi_overlay_conf }}"  

