---
# ansible-playbook -k -i hosts test_install_wittypi.yml -v
# ansible all -i hosts -k -m ansible.builtin.setup -u pi

# --extra-vars "xxx=yyy"

- name: Install ert-pi from scratch
  hosts: rpi_hosts
  remote_user: pi
  become: true
  vars:
    wittypi_git_repo: 'https://github.com/tingeman/Witty-Pi-4.git'
    wittypi_git_branch: develop # main
    local_tmp_dir: './tmp'
    finally_enable_ofs_bootro: false

  tasks:
    - name: Set overlayfs and bootro to disabled
      ansible.builtin.include_role:
        name: configure_overlayfs_and_bootro
      vars:
        enable_bootro: false
        enable_overlayfs: false
        allow_reboot: true

    # ==============================================================
    # Install packages
    # ==============================================================
    - name: install dependencies with apt-get
      ansible.builtin.package:   # or ansible.builtin.apt (for debian/ubuntu flavors)
        name: 
          - git
          - bc
        state: present
      # Result checked and OK

    # ==============================================================
    # Install python dependencies
    # ==============================================================
    - name: Install python dependencies
      ansible.builtin.include_role: 
        name: install_python_dependencies
      # Result checked and OK

    # ==============================================================
    # Install wittypi code
    # ==============================================================  
    - name: install wittypi
      ansible.builtin.include_role: 
        name: install_wittypi_from_git

    - name: Set overlayfs and bootro to enabled
      ansible.builtin.include_role:
        name: configure_overlayfs_and_bootro
      vars:
        enable_bootro: "{{ finally_enable_ofs_bootro }}"
        enable_overlayfs: "{{ finally_enable_ofs_bootro }}"
        allow_reboot: true

    - name: Collect overlayfs and bootro facts
      collect_overlayfs_bootro_fact:
