  # tasks file for configure_dhcp_server role

  - name: Install the isc-dhcp-server package 
    ansible.builtin.apt:
      name: isc-dhcp-server
      state: present
    register: apt_isc_dhcp_server

  - name: Configure isc-dhcp-server to use eth0
    ansible.builtin.lineinfile:
      path: /etc/default/isc-dhcp-server
      regexp: '(?i)^\s*INTERFACESv4\s*='
      line: 'INTERFACESv4="eth0"'
      state: present

  - name: Transfer and populate dhcpd.conf template
    ansible.builtin.template:
      src: dhcpd.conf.j2
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: u=rw,g=rw,o=rw
    debugger: on_failed
    vars:
      dhcp_settings: 
        local_domain_name: terrameterls
        authorative: true
        subnets:
          - { address: '192.168.23.0', mask: '255.255.255.0', pool_range_begin: '192.168.23.11', pool_range_end: '192.168.23.30', broadcast_address: '192.168.23.255' }
        hosts:
          - { hostname: 'LS209110003', mac_address: '02:AD:BE:EF:03:00', fixed_ip_address: '192.168.23.10' }
          
  - name: Implementing fix for restart of dhcp server
    block:
      - name: Check if isc-dhcp-server.service file exists
        ansible.builtin.stat:
          path: /etc/systemd/system/isc-dhcp-server.service
        register: stat_result

      - name: Generate isc-dhcp-server.service file if it does not exist
        ansible.builtin.command: cp /run/systemd/generator.late/isc-dhcp-server.service /etc/systemd/system
        when: not stat_result.stat.exists

      - name: Configure automatic restart  of isc-dhcp-server service
        community.general.ini_file:
          path: /etc/systemd/system/isc-dhcp-server.service
          section: "{{ item.section }}"
          option: "{{ item.option }}"
          value: "{{ item.value }}"
          state: present
          exclusive: "{{ item.exclusive }}"
        loop:
          - { section: 'Service', option: 'Restart', value: 'on-failure', exclusive: true }
          - { section: 'Service', option: 'RestartSec', value: '5', exclusive: true }
          - { section: 'Service', option: 'ExecStartPre', value: '/bin/sleep 10', exclusive: true }
          - { section: 'Install', option: 'WantedBy', value: 'multi-user.target', exclusive: true }

      # Not sure if we can have spaces around equal signs, so we remove them
      - name: Remove spaces around equal sign in /etc/systemd/system/isc-dhcp-server.service
        ansible.builtin.replace:
          path: /etc/systemd/system/isc-dhcp-server.service
          regexp: '[\s]+=[\s]+'
          replace: '='

      - name: Configure eth0 interface
        ansible.builtin.template:
          src: eth0.cfg.j2
          dest: /etc/network/interfaces.d/eth0.cfg
          force: true
          owner: root
          group: root
          mode: u=rw,g=rw,o=rw
        vars:
          eth0_static_address: '192.168.23.1'
          eth0_netmask: '255.255.255.0'
          eth0_broadcast_address: '192.168.23.255'
        debugger: on_failed

      - name: Force systemd to reload configs
        ansible.builtin.systemd:
          daemon_reload: true

      - name: Ensure isc-dhcp-server is enabled on boot
        ansible.builtin.systemd:
          name: isc-dhcp-server
          enabled: true