  # tasks file for configure_ntp role
  
  # ==============================================================
  # Configuring time related settings
  # ==============================================================

  - name: Install the NTP daemon 
    ansible.builtin.apt:
      name: ntp
      state: present

  - name: Set timezone variables
    copy: 
      content: 'Etc/UTC'
      dest: /etc/timezone
      mode: 0644
      backup: yes
    notify:
      - update timezone
  
  - name: remove lines from ntp.conf file
    ansible.builtin.lineinfile: 
      path: /etc/ntp.conf
      regexp: "{{ item.regexp }}"
      state: absent
    loop:
      - { regexp: '^[\s#]restrict[\s]+127.0.0.1' }
      - { regexp: '^[\s#]restrict[\s]+::1.*' }
      - { regexp: '^[\s#]Local users may interrogate' }
      - { regexp: '^[\s#]restrict[\s]+192.168.23.0' }
      - { regexp: '^[\s#]server[\s]+127.127.1.0' }
      - { regexp: '^[\s#]fudge[\s]+127.127.1.0' }
    notify:
      - restart ntp service

  - name: add lines to ntp.conf file
    ansible.builtin.lineinfile: 
      path: /etc/ntp.conf
      line: "{{ item }}"
      state: present
    loop:
      - ' '
      - '# Local users may interrogate the ntp server more closely.'
      - 'restrict 127.0.0.1'
      - 'restrict ::1'
      - ' '
      - '# Clients from this subnet can request time'
      - 'restrict 192.168.23.0 mask 255.255.255.0 nomodify notrap'
      - ' '
      - '# Use local clock if upstream server is not available'
      - 'server  127.127.1.0 # local clock'
      - 'fudge   127.127.1.0 stratum 3'
    notify:
      - restart ntp service