  - name: Install cron job to reboot daily at 04:00 UTC
    ansible.builtin.cron:
      name: "Safety precaution, always reboot at 04:00 UTC"
      minute: "00"
      hour: "04"
      job: "/usr/bin/bash {{ (dtuertpi_dir, 'sh_scripts', 'reboot_now.sh') | path_join }}  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: WittyPi Reschedule next boot every 15 min
    ansible.builtin.cron:
      name: "WittyPi Reschedule next boot every 15 min"
      # Workaround for overdue startup time causing an i2c bus lockup
      minute: "*/15"
      job: "/usr/bin/bash {{ (wittypi_dir, 'runScript.sh') | path_join }} 1 revise  >>{{ (usb_mount_point, 'logs', 'schedule.log') | path_join }}  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: Measure battery supply voltage
    ansible.builtin.cron:
      name: "Measure battery supply voltage"
      minute: "*/5"
      job: "/usr/bin/python3 {{ (dtuertpi_dir, 'io_scripts', 'log_voltage.py') | path_join }}  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: Check in with alive server after reboot
    ansible.builtin.cron:
      name: "Check in with alive server after reboot"
      special_time: reboot
      job: "sleep 240 && /usr/bin/python3 {{ (dtuertpi_dir, 'send_alive.py') | path_join }} \"rebooted\"  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: Check in with alive server every 4 hrs
    ansible.builtin.cron:
      name: "Check in with alive server every 4 hrs"
      minute: "55"
      hour: "*/4"
      job: "/usr/bin/python3 {{ (dtuertpi_dir, 'send_alive.py') | path_join }} \"cron_4hrs\"  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: Upload logs to server
    ansible.builtin.cron:
      name: "Upload logs to server"
      minute: "*/15"
      job: "/usr/bin/bash {{ (dtuertpi_dir, 'sh_scripts', 'upload_logs.sh') | path_join }}  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"

  - name: Check that ppp0 is up, and reset if it is not
    ansible.builtin.cron:
      name: "Check that ppp0 is up, and reset if it is not"
      minute: "20"
      job: "/usr/bin/bash {{ (dtuertpi_dir, 'sh_scripts', 'check_wan_status.sh') | path_join }}  2>>{{ (usb_mount_point, 'logs', 'cron_errors.log') | path_join }}"
