
- name: Ensure fstab passno=0 and dump=0 for rootfs
  ansible.posix.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "defaults,noatime"
    passno: '0'
    dump: '0'
    state: present
  with_items: "{{ ansible_mounts }}"
  when: "item.mount == '/'"

- name: Ensure fstab passno=0 and dump=0 for bootfs
  ansible.posix.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "defaults,flush"
    passno: '0'
    dump: '0'
    state: present
  with_items: "{{ ansible_mounts }}"
  when: "item.mount == '/boot'"

- name: Get USB disk partuuid
  command: "lsblk {{ usb_device }} -lno PARTUUID"
  register: lsblk_usb_partuuid

- name: Get USB disk fstype
  command: "lsblk {{ usb_device }} -lno FSTYPE"
  register: lsblk_usb_fstype

# - name: debug
#   ansible.builtin.debug:
#     msg: "{{ lsblk_usb_partuuid }}"

# - name: debug
#   ansible.builtin.debug:
#     msg: "{{ lsblk_usb_fstype }}"

- name: Ensure usb disk is mounted
  mount:
    name: "{{ usb_mount_point }}"
    src: "PARTUUID={{ lsblk_usb_partuuid.stdout }}"
    fstype: "{{ lsblk_usb_fstype.stdout }}"
    opts: "defaults,noatime,nofail"
    passno: '0'
    dump: '0'
    state: mounted

#lsblk /dev/sda1 -lno PARTUUID
#lsblk /dev/sda1 -f -lno FSTYPE
#PARTUUID=0dbb1829-01  /media/usb      ntfs    defaults,noatime,nofail   0       0

