---
host_hardware: raspberry_pi_4

# CURRENTLY DEFINED FOR ENTIRE GROUP OF HOSTS IN rpi_hosts.yml
# fan_on_temperature: 60000   # DegC * 1000
# enable_bluetooth: true
# enable_wifi: true

ssh_reverse_tunnel_port: 3333
ssh_server_user: "{{inventory_hostname}}"
ssh_server_ip: 192.38.64.71
ssh_server_port: 22
ssh_key_file: "/root/.ssh/{{inventory_hostname}}_sshkey"

usb_mount_point: /media/usb

# CURRENTLY DEFINED FOR ENTIRE GROUP OF HOSTS IN rpi_hosts.yml
# wittypi_default_power_state: 1            # 1 = TURN ON; 0 = STAY OFF, when power is connected 
# wittypi_low_voltage_threshold: 55         # threshold voltage * 10 (as integer)
# wittypi_recovery_voltage_threshold: 100   # threshold voltage * 10 (as integer)
# wittypi_schedule_file: turn_on_35min_every_hour_WAIT.wpi